CREATE TABLE IF NOT EXISTS `{table_name}`(
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `query` TEXT NOT NULL,
  `exception` TEXT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;